### ISSUE TITLE
[BUG] Disable Cosmetic Filtering Option is FORTNITE reverts back

### ISSUE THREAD

**Issue by techgamers2** [Dummerle/Rare#299]
**Describe the bug**
whenever new fortnite update comes " disable cosmetic filtering " gets uncheck 

**Screenshots**
![Screenshot 2023-06-20 174754](https://github.com/Dummerle/Rare/assets/44696073/ace6a938-5fe3-4c9b-9595-4026f42883a1)

how to reach this screen in rare coz i m also able to see this screen only when new update comes

**System information**

Please complete the following information
- Operating system: Windows 10
- Version [e.g. 1.6.2]
- Installation method : msi

**Additional context**

repair installation button should be available all the time

**Comment by loathingKernel** [comment]
> repair installation button should be available all the time

The "Repair" button is a available only if the verification fails, that's how it should work because "Repair" has certain requirements that are not satisfied otherwise.

Currently you can reach this screen either through "Repair" or "Update". The version of legendary we bundle with the Windows version doesn't support this use-case properly yet, the latest one should handle it better but we haven't updated our glue module to that yet.

**Comment by techgamers2** [comment]
So there is no way to see game option unless an update or any corruption comes in game ?

-------- Original Message --------

**Comment by loathingKernel** [comment]
At this moment, no, there isn't.

**Comment by techgamers2** [comment]
quick workaround is whenever new update comes always use " update with settings " option

**Comment by loathingKernel** [comment]
Btw, this should be properly fixed once https://github.com/Dummerle/Rare/pull/298/commits/12e6f48585d2aece2ca96dfd22e1f5f66ff5b343 is merged.
